default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") { "mysql_new_db" } %>
  username: <%= ENV.fetch("MYSQL_USER") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "root" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_TEST_DB") { "mysql_test_db" } %>

production:
  <<: *default
  database: <%= ENV["PRODUCTION_MYSQL_DB"] %>
  username: <%= ENV["PRODUCTION_MYSQL_USER"] %>
  password: <%= ENV["PRODUCTION_MYSQL_PASSWORD"] %>